version: '3'
services:
  auldfellas:
    build: auldfellas
    image: "auldfellas:latest"
    ports:
      - 1099
  dodgydrivers:
    build: dodgydrivers
    image: "dodgydrivers:latest"
    ports:
      - 1099
  girlpower:
    build: girlpower
    image: "girlpower:latest"
    ports:
      - 1099
