version: '3'

services:
  broker:
    build: broker
    networks:
      - default
    ports:
      - "8083:8083"
    expose:
      - 8083
  auldfellas:
    build: auldfellas
    networks:
      - default
    ports:
      - "8080:8080"
    expose:
      - 8080
    links:
      - broker
    depends_on:
      - broker
  girlpower:
    build: girlpower 
    networks:
      - default
    ports:
      - "8081:8081"
    expose:
      - 8081
    links:
      - broker
    depends_on:
      - broker
  dodgydrivers:
    build: dodgydrivers
    networks:
      - default
    ports:
      - "8082:8082"
    expose:
      - 8082
    links:
      - broker
    depends_on:
      - broker
